spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#these is the property you have to keep in the eureka server and also add @EnableEurekaServer in the main application file of eureka server



And Now these are the properties you have to keep in every Other microservice which you want to be discovered by the eureka server 
also add Discovery Client dependency .
# -------------------------------------------------------------------
# Eureka Client Configuration
# -------------------------------------------------------------------
eureka.client.register-with-eureka=true   // for registering with eureka
eureka.client.fetch-registry=true         // for enabling fetching by eureka server
eureka.instance.prefer-ip-address=true     // register by ip address not with name 
eureka.client.service-url.defaultZone=http://localhost:8761/eureka          // default zone 
eureka.instance.hostname=localhost
 
